---
title: "TT_EmploymenEarnings"
author: "Jeff Grayum"
date: "8/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries.        
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(gganimate)
library(gifski)
```

Loading datasets.
```{r}
tuesdata <- tidytuesdayR::tt_load('2021-02-23')

earn <- tuesdata$earn

employed <- tuesdata$employed
```

A bit of my own analysis before watching the screencast.
```{r}
earn %>%
  summary()

earn %>%
  view()

employed %>%
  summary()

employed %>%
  view()

earn %>%
  count(sex, sort = TRUE)

earn %>%
  group_by(sex, year) %>%
  summarize(mean_income = mean(median_weekly_earn),
            mean_persons = mean(n_persons)) %>%
  ggplot(aes(year, mean_income, color = sex, size = mean_persons)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(x = "Year",
       y = "Mean weekly income",
       title = "Mean weekly earned income",
       color = "Sex",
       size = "Mean persons") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_size_continuous(labels = comma)

#Very busy and sloppy.  How to group into larger age groups?
earn %>%
  group_by(year, age) %>%
  summarize(mean_age_income = mean(median_weekly_earn)) %>%
  ggplot(aes(year, mean_age_income, color = age)) +
  geom_line() +
  theme_few() +
  labs(x = "Year",
       y = "Mean weekly income", 
       color = "Age group",
       title = "Weekly earned income by age") +
  scale_y_continuous(labels = dollar)

earn %>%
  filter(age != "16 years and over",
         age != "25 years and over",
         age != "55 years and over") %>%
  ggplot(aes(age, median_weekly_earn, group = age)) +
  geom_boxplot() +
  labs(x = "", 
       y = "Median weekly income",
       title = "Median weekly income by age") +
  theme_hc() +
  theme(axis.text.x = element_text(angle = 90))


earn %>%
  ggplot(aes(sex, median_weekly_earn, group = sex)) +
  geom_boxplot() +
  labs(x = "",
       y = "Median weekly earnings",
       title = "Median weekly earnings by sex") +
  scale_y_continuous(labels = dollar) +
  theme_hc()

earn %>%
  ggplot(aes(race, median_weekly_earn, group = race)) +
  geom_boxplot() +
  labs(x = "",
       y = "Median weekly earnings",
       title = "Median weekly earnings by race") +
  scale_y_continuous(labels = dollar) +
  theme_hc()

earn %>%
  filter(race != "All Races",
         sex != "Both Sexes") %>%
  group_by(race, sex, year) %>%
  summarize(mean_employed = mean(n_persons, na.rm = TRUE)) %>%
  ggplot(aes(year, mean_employed, fill = race)) +
  geom_col() +
  labs(x = "Year", 
       y = "Mean employed",
       title = "Mean number of employed individuals",
       fill = "") +
  theme_few() +
  scale_y_continuous(labels = comma) 
```

Ok. Now for the screencast.
```{r}
employed %>%
  count(industry, sort = TRUE)

employed %>%
  count(industry, major_occupation, sort = TRUE)

employed %>%
  count(race_gender, sort = TRUE)

employed <- employed %>%
  mutate(dimension = case_when(
    race_gender == "TOTAL" ~ "Total",
    race_gender %in% c("Men", "Women") ~ "Gender",
    TRUE ~ "Race"
  )) 

employed %>% 
  view()

employed_cleaned <- employed %>%
  filter(!is.na(employ_n)) %>%
  mutate(industry = fct_lump(industry, 15, w = employ_n)) %>%
  mutate(industry = fct_reorder(industry, employ_n, sum)) 
  
employed_cleaned %>%
  filter(dimension == "Total") %>%
  ggplot(aes(year, employ_n, fill = industry)) +
  geom_col() +
  theme_few() +
  labs(x = "Year",
       y = "# Employed in industry",
       title = "Number of employeed in each industry",
       fill = "Industry") +
  scale_y_continuous(labels = comma) +
  theme(legend.position = "bottom") +
  expand_limits(y = 0)


employed_cleaned %>%
  filter(dimension == "Gender") %>%
  ggplot(aes(year, employ_n, fill = race_gender)) +
  geom_col() +
  theme_few() +
  labs(x = "Year",
       y = "# Employed in industry",
       title = "Number of employeed in each industry",
       fill = "Gender") +
  scale_y_continuous(labels = comma) +
  theme(legend.position = "bottom") +
  facet_wrap(~industry, scales = "free_y")

employed_cleaned %>%
  filter(year == "2020",
         industry == "Wholesale and retail trade") %>%
  view()
  
employed_cleaned %>%
  filter(dimension == "Gender") %>%
  group_by(industry, year, race_gender) %>%
  summarize(employed_n = sum(employ_n)) %>%
  ggplot(aes(year, employed_n, color = race_gender)) +
  geom_line() +
  theme_few() +
  labs(x = "Year",
       y = "# Employed in industry",
       title = "Number of employeed in each industry",
       color= "Gender") +
  scale_y_continuous(labels = comma) +
  theme(legend.position = "bottom") +
  facet_wrap(~industry, scales = "free_y") +
  expand_limits(y = 0)

```

Not a ton of variation between 2015 - 2019.  Let's look at 2019 - 2020.
```{r}
industry_2019_2020 <- employed_cleaned %>%
  filter(year %in% c(2019, 2020)) %>%
  group_by(year, industry, dimension, race_gender) %>%
  summarize(employ_n = sum(employ_n)) 

industry_2019_2020 %>%
  filter(dimension == "Total") %>%
  mutate(industry = fct_reorder(industry, employ_n, sum)) %>%
  ggplot(aes(year, employ_n, color = industry)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_color_discrete(guide = guide_legend(reverse = TRUE)) +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = 2019:2020) +
  labs(x = "",
       y = "# employed",
       color = "Industry", 
       title = "What industries were most affected by covid?") +
  theme_solarized_2()

compare_2019_2020 <- industry_2019_2020 %>%
  arrange(year) %>%
  group_by(industry, dimension, race_gender) %>%
  summarize(ratio = last(employ_n) / first(employ_n),
            change = ratio -1,
            employed_2019 = first(employ_n)) 

compare_2019_2020 %>%
  filter(dimension == "Total") %>%
  ungroup() %>% 
  mutate(industry = fct_reorder(industry, change)) %>%
  ggplot(aes(change, industry)) +
  geom_col() +
  scale_x_continuous(labels = percent) +
  labs(x = "% change",
       y = "Industry",
       title = "What industries were most impacted by covid?",
       caption = "Source: BLS") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman"))

compare_2019_2020 %>%
  filter(dimension == "Gender") %>%
  ungroup() %>% 
  mutate(industry = fct_reorder(industry, change)) %>%
  ggplot(aes(change, industry, fill = race_gender)) +
  geom_col(position = "dodge") +
  scale_x_continuous(labels = percent) +
  labs(x = "% change",
       y = "Industry",
       title = "What industries were most impacted by covid?",
       caption = "Source: BLS",
       fill = "") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_fill_discrete(guide = guide_legend(reverse = TRUE))

compare_2019_2020 %>%
  filter(dimension == "Gender") %>%
  ungroup() %>% 
  mutate(industry = fct_reorder(industry, change)) %>%
  ggplot(aes(change, industry, color = race_gender)) +
  geom_errorbarh(aes(xmin = 0, xmax = change), height = 0) +
  geom_point(aes(size = employed_2019, color = race_gender)) +
  scale_x_continuous(labels = percent) +
  scale_size_continuous(labels = comma, guide = FALSE) +
  labs(x = "% change",
       y = "Industry",
       title = "What industries were most impacted by covid?",
       caption = "Source: BLS",
       color = "",
       size = "# employed 2019",
       subtitle = "Size of point is proportional to size of industry in 2019") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_color_discrete(guide = guide_legend(reverse = TRUE)) +
  geom_vline(aes(xintercept = 0), lty = 2)
```

```{r}
compare_2019_2020 %>%
  filter(dimension == "Race") %>%
  ungroup() %>% 
  mutate(industry = fct_reorder(industry, change)) %>%
  ggplot(aes(change, industry, fill = race_gender)) +
  geom_col(position = "dodge") +
  scale_x_continuous(labels = percent) +
  labs(x = "% change",
       y = "Industry",
       title = "What industries were most impacted by covid?",
       caption = "Source: BLS",
       fill = "Race") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_fill_discrete(guide = guide_legend(reverse = TRUE))

compare_2019_2020 %>%
  filter(dimension == "Race") %>%
  ungroup() %>% 
  mutate(industry = fct_reorder(industry, change)) %>%
  ggplot(aes(change, industry, color = race_gender)) +
  geom_errorbarh(aes(xmin = 0, xmax = change, group = race_gender), height = 0,
                 position = position_dodge(width = 0.8)) +
  geom_point(aes(size = employed_2019, color = race_gender),
             position = position_dodge(width = 0.8)) +
  scale_x_continuous(labels = percent) +
  scale_size_continuous(labels = comma, guide = FALSE) +
  labs(x = "% change",
       y = "Industry",
       title = "What industries were most impacted by covid?",
       caption = "Source: BLS",
       color = "Race",
       size = "# employed 2019",
       subtitle = "Size of point is proportional to size of industry in 2019") +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(),
        text = element_text(family = "Times New Roman")) +
  scale_color_discrete(guide = guide_legend(reverse = TRUE)) +
  geom_vline(aes(xintercept = 0), lty = 2)

```

